/*
SQLyog Ultimate v12.4.3 (64 bit)
MySQL - 5.6.37-log : Database - dickow01
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`dickow01` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `dickow01`;

/*Table structure for table `CURSO` */

DROP TABLE IF EXISTS `CURSO`;

CREATE TABLE `CURSO` (
  `ID_CURSO` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(100) NOT NULL,
  `LOGO` longblob NOT NULL,
  `EXCLUIDO` bit(1) NOT NULL DEFAULT b'0',
  `MOMENTO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ID_SESSAO` int(11) NOT NULL,
  PRIMARY KEY (`ID_CURSO`),
  KEY `fk_CURSO_SESSAO1_idx` (`ID_SESSAO`),
  CONSTRAINT `fk_CURSO_SESSAO1` FOREIGN KEY (`ID_SESSAO`) REFERENCES `SESSAO` (`ID_SESSAO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `CURSO` */

/*Table structure for table `EVENTO` */

DROP TABLE IF EXISTS `EVENTO`;

CREATE TABLE `EVENTO` (
  `ID_EVENTO` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(200) NOT NULL,
  `DESCRICAO` text,
  `LOCALIZACAO` varchar(299) DEFAULT NULL,
  `DATA_HORA_INICIO` datetime DEFAULT NULL,
  `DATA_HORA_TERMINO` datetime DEFAULT NULL,
  `DATA_HORA_ATUALIZACAO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `LEMBRETE` smallint(6) NOT NULL DEFAULT '0',
  `ATIVO` bit(1) NOT NULL DEFAULT b'1',
  `EXCLUIDO` bit(1) NOT NULL DEFAULT b'0',
  `MOMENTO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ID_EVENTO_TIPO` int(11) NOT NULL,
  `ID_CURSO` int(11) NOT NULL,
  `ID_SESSAO` int(11) NOT NULL,
  `ID_RECORRENCIA` tinyint(4) DEFAULT NULL,
  `ID_EVENTO_ORIGEM` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_EVENTO`),
  KEY `fk_EVENTO_EVENTO_TIPO1_idx` (`ID_EVENTO_TIPO`),
  KEY `fk_EVENTO_CURSO1_idx` (`ID_CURSO`),
  KEY `fk_EVENTO_SESSAO1_idx` (`ID_SESSAO`),
  CONSTRAINT `fk_EVENTO_CURSO1` FOREIGN KEY (`ID_CURSO`) REFERENCES `CURSO` (`ID_CURSO`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_EVENTO_EVENTO_TIPO1` FOREIGN KEY (`ID_EVENTO_TIPO`) REFERENCES `EVENTO_TIPO` (`ID_EVENTO_TIPO`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_EVENTO_SESSAO1` FOREIGN KEY (`ID_SESSAO`) REFERENCES `SESSAO` (`ID_SESSAO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `EVENTO` */

/*Table structure for table `EVENTO_TIPO` */

DROP TABLE IF EXISTS `EVENTO_TIPO`;

CREATE TABLE `EVENTO_TIPO` (
  `ID_EVENTO_TIPO` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(200) NOT NULL,
  `COR` int(11) NOT NULL DEFAULT '0',
  `EXCLUIDO` bit(1) NOT NULL DEFAULT b'0',
  `MOMENTO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ID_SESSAO` int(11) NOT NULL,
  PRIMARY KEY (`ID_EVENTO_TIPO`),
  KEY `fk_EVENTO_TIPO_SESSAO1_idx` (`ID_SESSAO`),
  CONSTRAINT `fk_EVENTO_TIPO_SESSAO1` FOREIGN KEY (`ID_SESSAO`) REFERENCES `SESSAO` (`ID_SESSAO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `EVENTO_TIPO` */

/*Table structure for table `LOG` */

DROP TABLE IF EXISTS `LOG`;

CREATE TABLE `LOG` (
  `ID_LOG` int(11) NOT NULL AUTO_INCREMENT,
  `ID_SESSAO` int(11) NOT NULL,
  `DADOS` varchar(65353) NOT NULL,
  `MOMENTO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_LOG`),
  KEY `ID_SESSAO` (`ID_SESSAO`),
  CONSTRAINT `FK_LOG_SESSAO1` FOREIGN KEY (`ID_SESSAO`) REFERENCES `SESSAO` (`ID_SESSAO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `LOG` */

/*Table structure for table `PERMISSAO` */

DROP TABLE IF EXISTS `PERMISSAO`;

CREATE TABLE `PERMISSAO` (
  `ID_PERMISSAO` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(100) NOT NULL,
  `MOMENTO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_PERMISSAO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `PERMISSAO` */

/*Table structure for table `SESSAO` */

DROP TABLE IF EXISTS `SESSAO`;

CREATE TABLE `SESSAO` (
  `ID_SESSAO` int(11) NOT NULL AUTO_INCREMENT,
  `MOMENTO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ID_USUARIO` int(11) NOT NULL,
  PRIMARY KEY (`ID_SESSAO`),
  KEY `fk_SESSAO_USUARIO1_idx` (`ID_USUARIO`),
  CONSTRAINT `FK_SESSAO_USUARIO1` FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIO` (`ID_USUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;

/*Data for the table `SESSAO` */

insert  into `SESSAO`(`ID_SESSAO`,`MOMENTO`,`ID_USUARIO`) values 
(1,'2018-04-03 21:38:11',1),
(2,'2018-04-05 00:01:00',1),
(3,'2018-04-10 23:46:00',1),
(4,'2018-04-10 23:48:00',1),
(5,'2018-04-10 23:49:00',1),
(6,'2018-04-11 00:10:00',1);

/*Table structure for table `USUARIO` */

DROP TABLE IF EXISTS `USUARIO`;

CREATE TABLE `USUARIO` (
  `ID_USUARIO` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(255) NOT NULL,
  `SENHA` varchar(50) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `EXCLUIDO` bit(1) NOT NULL DEFAULT b'0',
  `MOMENTO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ID_SESSAO` int(11) NOT NULL,
  PRIMARY KEY (`ID_USUARIO`),
  KEY `fk_USUARIO_SESSAO1_idx` (`ID_SESSAO`),
  CONSTRAINT `fk_USUARIO_SESSAO1` FOREIGN KEY (`ID_SESSAO`) REFERENCES `SESSAO` (`ID_SESSAO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Data for the table `USUARIO` */

insert  into `USUARIO`(`ID_USUARIO`,`NOME`,`SENHA`,`EMAIL`,`EXCLUIDO`,`MOMENTO`,`ID_SESSAO`) values 
(1,'Andreves Dickow','123','andreves@dickow.me','\0','2018-04-03 21:39:16',1);

/*Table structure for table `USUARIO_PERMISSAO` */

DROP TABLE IF EXISTS `USUARIO_PERMISSAO`;

CREATE TABLE `USUARIO_PERMISSAO` (
  `ID_USUARIO_PERMISSAO` int(11) NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` int(11) NOT NULL,
  `ID_PERMISSAO` int(11) NOT NULL,
  PRIMARY KEY (`ID_USUARIO_PERMISSAO`),
  KEY `ID_USUARIO` (`ID_USUARIO`),
  KEY `ID_PERMISSAO` (`ID_PERMISSAO`),
  CONSTRAINT `FK_USUARIO_PERMISSAO_PERMISSAO1` FOREIGN KEY (`ID_PERMISSAO`) REFERENCES `PERMISSAO` (`ID_PERMISSAO`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_USUARIO_PERMISSAO_USUARIO1` FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIO` (`ID_USUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `USUARIO_PERMISSAO` */

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
