USE radiske;

DELIMITER $$
create TRIGGER SALVAR_LOG_RECORRENCIA
AFTER UPDATE 
ON radiske.RECORRENCIA
FOR EACH ROW
BEGIN
	SET @id := (SELECT ID_SESSAO FROM SESSAO ORDER BY ID_SESSAO DESC LIMIT 1);
	INSERT INTO LOG (ID_SESSAO, DADOS) VALUES (@id, CONCAT('{"ID_RECORRENCIA": ' , OLD.ID_RECORRENCIA , ', "DESCRICAO": "' , OLD.DESCRICAO , '"}'));
END;
$$