-- PERMISSOES
INSERT INTO 'PERMISSAO' ('ID_PERMISSAO', 'NOME') VALUES ('1', 'TELA_USUARIO');
INSERT INTO 'PERMISSAO' ('ID_PERMISSAO', 'NOME') VALUES ('2', 'TELA_CURSO');
INSERT INTO 'PERMISSAO' ('ID_PERMISSAO', 'NOME') VALUES ('3', 'TELA_EVENTO');
INSERT INTO 'PERMISSAO' ('ID_PERMISSAO', 'NOME') VALUES ('4', 'TELA_TIPO_EVENTO');
