USE radiske;

DELIMITER $$
CREATE TRIGGER SALVAR_LOG_USUARIO_PERMISSAO
AFTER UPDATE 
ON radiske.USUARIO_PERMISSAO
FOR EACH ROW
BEGIN
	SET @id := (SELECT ID_SESSAO FROM SESSAO ORDER BY ID_SESSAO DESC LIMIT 1);
	INSERT INTO LOG (ID_SESSAO, DADOS) VALUES (@id, CONCAT('{"ID_USUARIO_PERMISSAO": ' + OLD.ID_USUARIO_PERMISSAO + ', "ID_USUARIO": ' + OLD.ID_USUARIO + ', "ID_PERMISSAO": ' + OLD.ID_PERMISSAO + '}'));
END;
$$