USE radiske;

DELIMITER $$
CREATE TRIGGER SALVAR_LOG_CURSO
AFTER UPDATE 
ON radiske.CURSO
FOR EACH ROW
BEGIN
	SET @id := (SELECT ID_SESSAO FROM SESSAO ORDER BY ID_SESSAO DESC LIMIT 1);
	INSERT INTO LOG (ID_SESSAO, DADOS) VALUES (@id, CONCAT('{"ID_CURSO": ' + OLD.ID_CURSO + ', "NOME": "' + OLD.NOME + '", "LOGO": "' + OLD.LOGO + '", "EXCLUIDO": ' + OLD.EXCLUIDO + ', "MOMENTO": ' + OLD.MOMENTO + ', "ID_SESSAO": ' + OLD.ID_SESSAO + '}'));
END;
$$