DELIMITER ||
DROP TRIGGER IF EXISTS SALVAR_LOG_CURSO;
CREATE TRIGGER SALVAR_LOG_CURSO
AFTER UPDATE 
ON dickow01.CURSO
FOR EACH ROW
BEGIN
	SELECT @id := ID_SESSAO FROM SESSAO ORDER BY ID_SESSAO DESC LIMIT 1;
	INSERT INTO LOG (ID_SESSAO, DADOS) VALUES (@id, 'ALTERADO');
END; ||