USE appamf;

DELIMITER $$
CREATE TRIGGER SALVAR_LOG_EVENTO_TIPO
AFTER UPDATE 
ON appamf.evento_tipo
FOR EACH ROW
BEGIN
	SELECT @id := ID_SESSAO FROM SESSAO ORDER BY ID_SESSAO DESC LIMIT 1;
	INSERT INTO LOG (ID_SESSAO, DADOS) VALUES (@id, '{"ID_EVENTO_TIPO": ' + OLD.ID_EVENTO_TIPO + ', "NOME": "' + OLD.NOME + '", "COR": ' + OLD.COR + ', "EXCLUIDO": ' + OLD.EXCLUIDO + ', "MOMENTO": ' + OLD.MOMENTO + ', "ID_SESSAO": ' + OLD.ID_SESSAO + '}');
END;
$$