USE appamf;

DELIMITER $$
CREATE TRIGGER SALVAR_LOG_PERMISSAO
AFTER UPDATE 
ON appamf.permissao
FOR EACH ROW
BEGIN
	SELECT @id := ID_SESSAO FROM SESSAO ORDER BY ID_SESSAO DESC LIMIT 1;
	INSERT INTO LOG (ID_SESSAO, DADOS) VALUES (@id, '{"ID_PERMISSAO": ' + OLD.ID_PERMISSAO + ', "NOME": "' + OLD.NOME + '", "MOMENTO": ' + OLD.MOMENTO + '}');
END;
$$