USE radiske;

DELIMITER $$
CREATE TRIGGER SALVAR_LOG_EVENTO_TIPO
AFTER UPDATE 
ON radiske.EVENTO_TIPO
FOR EACH ROW
BEGIN
	SET @id := (SELECT ID_SESSAO FROM SESSAO ORDER BY ID_SESSAO DESC LIMIT 1);
	INSERT INTO LOG (ID_SESSAO, DADOS) VALUES (@id, CONCAT('{"ID_EVENTO_TIPO": ' + OLD.ID_EVENTO_TIPO + ', "NOME": "' + OLD.NOME + '", "COR": ' + OLD.COR + ', "EXCLUIDO": ' + OLD.EXCLUIDO + ', "MOMENTO": ' + OLD.MOMENTO + ', "ID_SESSAO": ' + OLD.ID_SESSAO + '}'));
END;
$$