USE radiske;

DELIMITER $$
CREATE TRIGGER SALVAR_LOG_EVENTO_TIPO
AFTER UPDATE 
ON radiske.EVENTO_TIPO
FOR EACH ROW
BEGIN
	SET @id := (SELECT ID_SESSAO FROM SESSAO ORDER BY ID_SESSAO DESC LIMIT 1);
	SET @cor := (SELECT CAST(COR AS CHAR(50)) FROM appamf.evento_tipo WHERE ID_EVENTO_TIPO = OLD.ID_EVENTO_TIPO);
	INSERT INTO LOG (ID_SESSAO, DADOS) VALUES (@id, CONCAT('{"ID_EVENTO_TIPO": ' , OLD.ID_EVENTO_TIPO , ', "NOME": "' , OLD.NOME , '", "COR": "' , @cor , '", "MOMENTO": "' , OLD.MOMENTO , '", "ID_SESSAO": ' , OLD.ID_SESSAO , '}'));
END;
$$