CREATE TRIGGER SALVAR_LOG_CURSO AFTER UPDATE ON CURSO
FOR EACH ROW
BEGIN
	DECLARE x INT;
	DECLARE y JSON;
   SET x = (SELECT ID_SESSAO FROM SESSAO ORDER BY ID_SESSAO DESC LIMIT 1);
   SET y = (SELECT * FROM CURSO WHERE ID = NEW.ID);
	INSERT INTO LOG(ID_SESSAO, DADOS) VALUES (x, y)
END;