CREATE TRIGGER SALVAR_LOG AFTER UPDATE ON DATABASE
FOR EACH ROW
BEGIN
INSERT INTO LOG(ID_SESSAO, DADOS) VALUES (SELECT ID_SESSAO FROM SESSAO ORDER BY ID_SESSAO DESC LIMIT 1,
														SELECT * FROM CURSO ORDER BY ID_CURSO DESC LIMIT 1)
END;


SELECT ID_SESSAO FROM SESSAO ORDER BY ID_SESSAO DESC LIMIT 1