USE appamf;

DELIMITER $$
CREATE TRIGGER SALVAR_LOG_RECORRENCIA
AFTER UPDATE 
ON appamf.recorrencia
FOR EACH ROW
BEGIN
	SELECT @id := ID_SESSAO FROM SESSAO ORDER BY ID_SESSAO DESC LIMIT 1;
	INSERT INTO LOG (ID_SESSAO, DADOS) VALUES (@id, '{"ID_RECORRENCIA": ' + OLD.ID_RECORRENCIA + ', "DESCRICAO": "' + OLD.DESCRICAO + '"}');
END;
$$