USE appamf;

DELIMITER $$
CREATE TRIGGER SALVAR_LOG_USUARIO
AFTER UPDATE 
ON appamf.usuario
FOR EACH ROW
BEGIN
	SELECT @id := ID_SESSAO FROM SESSAO ORDER BY ID_SESSAO DESC LIMIT 1;
	INSERT INTO LOG (ID_SESSAO, DADOS) VALUES (@id, '{"ID_USUARIO": ' + OLD.ID_USUARIO + ', "NOME": "' + OLD.NOME + '", "SENHA": "' + OLD.SENHA + '", "EMAIL": "' + OLD.EMAIL + '", "EXCLUIDO": ' + OLD.EXCLUIDO + ', "MOMENTO": ' + OLD.MOMENTO + ', "ID_SESSAO": ' + OLD.ID_SESSAO + '}');
END;
$$